# Generated by Django 4.2.7 on 2023-11-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CO2EmissionsBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of the benchmark data")),
                (
                    "total_emissions",
                    models.FloatField(help_text="Total CO2 emissions in megatonnes"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectricityProductionBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of the benchmark data")),
                (
                    "total_production",
                    models.FloatField(
                        help_text="Total electricity production in gigawatt-hours (GWh)"
                    ),
                ),
            ],
        ),
    ]
