# Generated by Django 4.2.7 on 2023-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2_prod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2emissionsbenchmark',
            name='total_emissions',
        ),
        migrations.RemoveField(
            model_name='electricityproductionbenchmark',
            name='total_production',
        ),
        migrations.AddField(
            model_name='co2emissionsbenchmark',
            name='value',
            field=models.FloatField(default=0, help_text='Total CO2 emissions in megatonnes per year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricityproductionbenchmark',
            name='value',
            field=models.FloatField(default=0, help_text='Total electricity production in Terra Watt-hours (TWh) per year'),
            preserve_default=False,
        ),
    ]
