# Generated by Django 4.2.7 on 2023-11-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("h2_prod", "0002_remove_co2emissionsbenchmark_total_emissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="co2emissionsbenchmark",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional information about the benchmark data"
            ),
        ),
        migrations.AddField(
            model_name="electricityproductionbenchmark",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional information about the benchmark data"
            ),
        ),
    ]
