# Generated by Django 4.2.7 on 2023-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("h2_prod", "0004_alter_co2emissionsbenchmark_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="co2emissionsbenchmark",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the CO2 emissions source",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="electricityproductionbenchmark",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the electricity production source",
                max_length=100,
                null=True,
            ),
        ),
    ]
