# Generated by Django 4.2.7 on 2023-12-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("h2_prod", "0005_co2emissionsbenchmark_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CO2EmissionsBenchmark", new_name="CO2eEmissionsBenchmark",
        ),
    ]
